### ISSUE TITLE
It can't display on MIUI system  like xiaomi mobile..

### ISSUE THREAD

**Issue by MIkeeJY** [irimiaionut/ParallaxImageView#1]
It can't display on MIUI system  like xiaomi mobile,how to solve it...

**Comment by irimiaionut** [comment]
Hey MlkeeJY, can you paste the error? I could help you on this but I don't have a Xiaomi device.

**Comment by MIkeeJY** [comment]
hi,man,the problem is the demo just plays no animation only on MIUI 5 system,I don't know why,there's no error log...

**Comment by irimiaionut** [comment]
http://xiaomi.eu/community/threads/sensors-not-working-multi-3-11-15.23288/

"I recently bought a Xiaomi Red Rice from merimobiles and the phone I got has an MIUI 3.11.15 multi language version. I've added the Antutu benchmark and I saw that some of the sensors are not supported as they should be ( g-sensor, gyro sensor, linear acceleration sensor & rotation vector sensor). Propably that's why trying to change the led lights for notifications doesn't work and forces app to close. Any suggestions of which version I should use? "

Can you please check with Antutu if the sotware sensor rotation vector is available?

**Comment by MIkeeJY** [comment]
thx man,my device is XiaoMi 3 MIUI 4.8.22,maybe I should update the system to MIUI 6 and then try it again...
